### ISSUE TITLE
Repository Name

### ISSUE THREAD

**Issue by lorepirri** [ReDI-School/redi-js-nrw#1]
The slides should point to a GitHub Pages link (e.g. in [Readme.md](https://github.com/ReDI-School/nrw-js#readme)):
```
https://redi-school.github.io/nrw/#/
```

~But the GitHub Pages are not set.~ I did activate them, and ~I will open a PR for updating~ I updated the [Readme.md](https://github.com/ReDI-School/nrw-js#readme) links.

However, I had a look at other courses from Berlin and I see that for the repositories name, they use the format:

`<curriculum>-<chapter>-<year>-<semester>` (e.g. `js-berlin-2020-spring`)

so, if we follow this naming convention, this one of the NRW for this semester should be: `js-nrw-2021-fall` and not `nrw-js`.

In this way, we will be able to edit, update the slides for this semester, and then archive the repo.

But I also see other repos that do not follow this standard, so maybe you decided for a one repository for all semesters.

Let me know, in case I will rename the repository (all the links will need to be updated, though)

**Comment by lorepirri** [comment]
Github pages activated, slides are active, links in [Readme.me](Readme.me) updated.

Consider the option of changing the name of the repository. @takuya-redi @CosimoReDI .

**Comment by takuya-redi** [comment]
Thank you so much @lorepirri for activating the repository and updating the links. I see the point regarding the naming format. Now I updated it as "js-nrw-2021-fall" and also links accordingly on [Readme.md](https://github.com/ReDI-School/js-nrw-2021-fall/issues/Readme.me). With that, I close the issue.
