### ISSUE TITLE
Update Semester, Year, and Date in Slides

### ISSUE THREAD

**Issue by lorepirri** [ReDI-School/redi-js-nrw#2]
Each lesson has still `SPRING 2020` and the old date of the spring semester of the JS course in Berlin.

Update to `FALL 2021` and each day of lesson of the semester.

**Comment by RajshreeVats** [comment]
Hey, I am new to open source. can I be assigned to do the required enhancement?

**Comment by lorepirri** [comment]
Hi @RajshreeVats, yeah sure! 

Please, fork the repository on your local machine, apply the proposed changes and [open a PR](https://opensource.guide/how-to-contribute/#opening-a-pull-request). 

Should you need any guidance, please drop a comment! Thanks for helping!

**Comment by RajshreeVats** [comment]
Thanks, @lorepirri for the help!!

**Comment by lorepirri** [comment]
@RajshreeVats here you find the:

<details><summary>List of lessons with date, time, and number</summary>
<p>

```
Di., Sept. 14, 	19:00 – 21:00	1
Do., Sept. 16, 	19:00 – 21:00	2

Di., Sept. 21, 	19:00 – 21:00	3
Do., Sept. 23, 	19:00 – 21:00	4

Di., Sept. 28, 	19:00 – 21:00	5
Do., Sept. 30, 	19:00 – 21:00	-

Di., Okt. 5, 	19:00 – 21:00	6
Do., Okt. 7, 	19:00 – 21:00	7

Di., Okt. 12, 	19:00 – 21:00	8
Do., Okt. 14, 	19:00 – 21:00	9

Di., Okt. 19, 	19:00 – 21:00	10
Do., Okt. 21, 	19:00 – 21:00	-

Di., Okt. 26, 	19:00 – 21:00	11
Do., Okt. 28, 	19:00 – 21:00	12

Di., Nov. 2, 	19:00 – 21:00	13
Do., Nov. 4, 	19:00 – 21:00	14

Di., Nov. 9, 	19:00 – 21:00	15
Do., Nov. 11, 	19:00 – 21:00	-

Di., Nov. 16, 	19:00 – 21:00	16
Do., Nov. 18, 	19:00 – 21:00	17

Di., Nov. 23, 	19:00 – 21:00	18
Do., Nov. 25, 	19:00 – 21:00	19

Di., Nov. 30, 	19:00 – 21:00	20
Do., Dez. 2, 	19:00 – 21:00	-

Di., Dez. 7, 	19:00 – 21:00	21
Do., Dez. 9, 	19:00 – 21:00	22

Di., Dez. 14, 	19:00 – 21:00	23
Do., Dez. 16, 	19:00 – 21:00	24
```

</p>
</details>
